version: '3.8'
services:
  http-honeypot:
    build: ./http-honeypot
    container_name: http-honeypot
    ports:
      - "80:80"
    networks:
      - honeypot-net
    restart: unless-stopped

  ftp-honeypot:
    build: ./ftp-honeypot
    container_name: ftp-honeypot
    ports:
      - "21:21"
    networks:
      - honeypot-net
    restart: unless-stopped

  rdp-honeypot:
    build: ./rdp-honeypot
    container_name: rdp-honeypot
    ports:
      - "3389:3389"
    networks:
      - honeypot-net
    restart: unless-stopped

  mysql-honeypot:
    build: ./mysql-honeypot
    container_name: mysql-honeypot
    ports:
      - "3306:3306"
    networks:
      - honeypot-net
    restart: unless-stopped

  ssh-honeypot:
    build: ./ssh-honeypot
    container_name: ssh-honeypot
    ports:
      - "2222:2222"
    networks:
      - honeypot-net
    restart: unless-stopped

networks:
  honeypot-net:
    driver: bridge
